services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile

    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /workspace
    #       ignore:
    #         - .venv/

    #     # Rebuild the image on changes to the `pyproject.toml`
    #     - action: rebuild
    #       path: ./pyproject.toml

    volumes:
     - .:/workspace
    # - /workspace/.venv
      
    #network_mode: service:db
    # depends_on:
    #   - postgres
    command: sleep infinity
    ports:
      - "8050:8050"

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"  # http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
  postgres_data: