services:
  devcontainer:
    container_name: devcontainer
    # image: vival-devcontainer:latest
    build:
     context: .
     dockerfile: Dockerfile
    restart: always
    volumes:
     - .:/workspace
    # command: ["sleep", "infinity"]
    command: python /workspace/src/app.py
    ports:
      - "8050:8050"
    expose:
      - "8050"
    networks:
     - default

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"  # http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
    networks:
      - default


  certbot:
    image: certbot/certbot
    container_name: certbot
    command: certonly --webroot --webroot-path=/var/www/certbot -d vival.ai
    volumes:
      - ./certs:/etc/letsencrypt  # Share certs volume with nginx
      - ./certbot-webroot:/var/www/certbot  # Temporary directory for webroot
    networks:
      - default
volumes:
  pgadmin_data:
  postgres_data: